### ISSUE TITLE
INTEGER() can only be applied to a 'integer', not a 'character'

### ISSUE THREAD

**Issue by scworland** [gbm-developers/gbm3#108]
I am receiving this error when I tried to use the most recent gbm using devtools. I have not seen this error in the past. An example is below:

```
y <- rgamma(100, 2, scale = 1/2)

x <- data.frame(x1 = y + rnorm(100,0,3),
                x2 = y + rnorm(100,4,5))

fit <- gbm.fit(x,y,distribution="gamma")
```

Here is the error:

```
Error in gbm.fit(x, y, distribution = "gamma") : 
INTEGER() can only be applied to a 'integer', not a 'character'
```

**Comment by pdmetcalfe** [comment]
Umm... it works for me; I'm going to need a bit more info?

**Comment by scworland-usgs** [comment]
Thank you, it is obviously something on my end. Let me look into it and report back and close the issue when I figure something out.  I have been having conflicts with the rcpp package, and I suspect that my problem has something to do with that.

**Comment by scworland** [comment]
I did a complete re-install of R and Rtools and it works fine now. Unfortunately I cannot say what the issue was, but only that it is not something wrong with the gbm package!
