### ISSUE TITLE
Improvement for coxph

### ISSUE THREAD

**Issue by harrysouthworth** [gbm-developers/gbm3#11]
_From @jeffwong on June 3, 2014 4:30_

Would really appreciate the ability to use intervals in the Surv class, so instead of passing Surv(time, censor indicator) it would be great to pass Surv(start time, end time, censor indicator).  This would require rewriting some of the C++ code because adding this flexibility implies that at a particular time t not all records are part of the risk set.  In the current version, as long as the record is not censored it is in the risk set, but with a start time and end time we must have t >= start time and t < end time in order to be in the risk set

_Copied from original issue: harrysouthworth/gbm#21_

**Comment by pdmetcalfe** [comment]
Done, I hope. Testers welcome.
