### ISSUE TITLE
Error fitting and predicting "gbm" not available for .Call() for package "gbm"

### ISSUE THREAD

**Issue by JesseLimtiaco** [gbm-developers/gbm3#140]
Hello,

   I seem to run into errors fitting and predicting with gbm3.  Below is the example from the vignette.  I get an error that the C++ function isn't available for package "gbm".  Is this a namespace issue?  The call to the gbm C++ function takes in a "PACKAGE" argument as gbm, should it now be gbm3?

N <- 1000
X1 <- runif(N)
X2 <- runif(N)
X3 <- factor(sample(letters[1:4],N,replace=T))
mu <- c(-1,0,1,2)[as.numeric(X3)]

p <- 1/(1+exp(-(sin(3*X1) - 4*X2 + mu)))
Y <- rbinom(N,1,p) # response
 
# Normalized weights for each observation
w <- rexp(N)
w <- N*w/sum(w)

# Offset is set to 0
offset <- rep(0, N)
 
# Collate data
data <- data.frame(Y=Y,X1=X1,X2=X2,X3=X3)
bern_dist <- gbm_dist("Bernoulli")
train_params <- training_params(num_trees = 2000, interaction_depth = 3, num_train=nrow(data), num_features = 3)
fit <- gbm3::gbmt(Y ~ X1 + X2 + X3, distribution=bern_dist, data=data, weights = w, offset=offset, train_params = train_params, cv_folds=5, keep_gbm_data=TRUE)

**# Error in .Call("gbm", Y = as.matrix(as.data.frame(y_input)), intResponse = as.matrix(cbind(gbm_dist_obj$strata,  : 
  "gbm" not available for .Call() for package "gbm"**

From gbm_call.R:

fit <- .Call("gbm",
                Y=as.matrix(as.data.frame(y_input)),
                intResponse = as.matrix(cbind(gbm_dist_obj$strata, gbm_dist_obj$sorted)),
                Offset=as.double(gbm_data_obj$offset),
                X=as.matrix(as.data.frame(gbm_data_obj$x)),
                X.order=as.integer(gbm_data_obj$x_order),
                weights=as.double(gbm_data_obj$weights),
                Misc=get_misc(gbm_dist_obj),
                prior.node.coeff.var = ifelse(is.null(gbm_dist_obj$prior_node_coeff_var), as.double(0),
                                                         as.double(gbm_dist_obj$prior_node_coeff_var)),
                id = as.integer(train_params$id),
                var.type=as.integer(var_container$var_type),
                var.monotone=as.integer(var_container$var_monotone),
                distribution=gbm_call_dist_name(gbm_dist_obj),
                n.trees=as.integer(train_params$num_trees),
                interaction.depth=as.integer(train_params$interaction_depth),
                n.minobsinnode=as.integer(train_params$min_num_obs_in_node),
                shrinkage=as.double(train_params$shrinkage),
                bag.fraction=as.double(train_params$bag_fraction),
                nTrainRows=as.integer(train_params$num_train_rows),
                nTrainObs = as.integer(train_params$num_train),
                mFeatures=as.integer(train_params$num_features),
                fit.old=as.double(NA),
                n.cat.splits.old=as.integer(0),
                n.trees.old=as.integer(0),
                par_details,
                verbose=as.integer(is_verbose),
                PACKAGE = "gbm")

**Comment by bgreenwell** [comment]
Yes, there is still some package renaming that needs to be done before gbm3 will work properly. If no one else does, I should be able to get to it this weekend.

**Comment by pdmetcalfe** [comment]
I have patch pending.

I have clearly been spoilt by using automatically generated Rcpp wrappers in other work.

**Comment by pdmetcalfe** [comment]
Done, with luck.
