### ISSUE TITLE
"gbm" not available for .Call for package "gbm"

### ISSUE THREAD

**Issue by gravesee** [gbm-developers/gbm3#143]
I did my due diligence trying to troubleshoot this on my own. I am avid user of the first gbm package and would like to switch to gbm3. However, when trying to run the bernoulli demo I receive the following error:

```
Error in .Call("gbm", Y = as.matrix(as.data.frame(y_input)), intResponse = as.matrix(cbind(gbm_dist_obj$strata,  : 
  "gbm" not available for .Call() for package "gbm"
```

This happens when the `gbm` function is called in the demo. I have tried installing with `devtools::install_github` as well as by cloning the repository and building with both Rstudio and `R CMD install` with `--no-multiarch` option. Both produce the same error. 

Any ideas on what can cause this? I have tried everything I can think of.

**SessionInfo:**

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gbm3_2.2

loaded via a namespace (and not attached):
[1] Matrix_1.2-6    tools_3.3.0     survival_2.39-2 Rcpp_0.12.10   
[5] splines_3.3.0   grid_3.3.0      lattice_0.20-33
```

**Comment by bgreenwell** [comment]
It runs fine on my machine. What is ```gbm3_2.2```? Try

```r
detach("package:gbm3_2.2")
demo("bernoulli")
```

**Comment by bgreenwell** [comment]
Works fine on my machine? Did you reinstall the GitHub version after this morning's patch?

**Comment by gravesee** [comment]
Thanks I updated my repo with today's patch and it works now.
