### ISSUE TITLE
Modifying the bernouilli loss function

### ISSUE THREAD

**Issue by AurelieLemmens** [gbm-developers/gbm3#153]
Hi,
First, thanks for this great package! it is just amazing. 

I would like to modify the Bernouilli loss function in the following way:

**Current:** 
```

loss.BernoulliGBMDist <- function(y, predictions, weights, offset, distribution_obj, baseline=rep(0, length(y))) {
  return(-2*weighted.mean(y*(predictions+offset) - log(1+exp(predictions+offset)), weights) - baseline)
  }
```

**Modified:**
```

loss.BernoulliGBMDist <- function(y, predictions, weights, offset, distribution_obj, baseline=rep(0, length(y))) {
  return(-2*weighted.mean(weights*(predictions+offset) - log(1+exp(weights*(predictions+offset))), abs(weights)) - baseline)
}
```

To do so, I use the following code:
`fixInNamespace("loss.BernoulliGBMDist", "gbm3") `
and edit the function

when I check the function using
`gbm3:::loss.BernoulliGBMDist `
it seems to work. However, when I estimate the model using `gbm3::gbm(...)`  nothing changes.

Would someone be able to help?

thanks in advance!

Aurelie

**Comment by pdmetcalfe** [comment]
It doesn't work like that, I'm afraid. Those loss functions aren't really used inside gbm; only in the permutation-based relative importance. If you want to modify the loss functions that are actually really used for model fitting, you need to go and fiddle inside the C++ code, and that's a much less pleasant job!
