### ISSUE TITLE
Suggest adding "build_vignettes = TRUE" to "devtools" install instructions.

### ISSUE THREAD

**Issue by jasmyace** [gbm-developers/gbm3#162]
I see your `gbm3` repo includes vignettes.  Unfortunately, after your `devtools`-instructed install, I could not find them locally (on my Mac).  That is to say, I ran 

```r
library("devtools")
install_github("gbm-developers/gbm3")

browseVignettes("gbm3")
```

and came up empty.  

To remedy, I reinstalled, explicitly setting `build_vignettes = TRUE` (and `force = TRUE` to force a re-install)  

```r
library("devtools")
install_github("gbm-developers/gbm3", build_vignettes = TRUE, force = TRUE)

browseVignettes("gbm3")
```

I now see the four vignettes.  Assuming my experience is not unique, a slight instruction update on your landing-page `README` may aid the more casual installer.

**Comment by gregridgeway** [comment]
Good suggestion. Fixed
