### ISSUE TITLE
Incorrect prediction with new levels due to invalid memory addresses

### ISSUE THREAD

**Issue by pat-oreilly** [gbm-developers/gbm3#18]
```
d <- data.frame(x=as.factor(1:20), y=1:20)

train <- d[1:10,]
test  <- d[11:20,]

p <- rep(0, 10)

while(sum(abs(p)) == 0)
{
    g <- gbm(y ~ x,
             distribution="gaussian",
             bag.fraction=1,
             data=train, 
             n.trees=1,
             shrinkage=1,
             n.minobsinnode=1)

    p <- predict(g, newdata=test, n.trees=1) - g$initF
}

pretty.gbm.tree(g, 1)
#  SplitVar SplitCodePred LeftNode RightNode MissingNode ErrorReduction Weight Prediction
#0        0           0.0        1         2           3           62.5     10        0.0
#1       -1          -2.5       -1        -1          -1            0.0      5       -2.5
#2       -1           2.5       -1        -1          -1            0.0      5        2.5
#3       -1           0.0       -1        -1          -1            0.0     10        0.0

g$c.splits[[1]]
#[1] -1 -1 -1 -1 -1  1  1  1  1  1

print(p)
#[1] 0.0 2.5 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
```

In this example the test data has 10 levels unseen during training. The predictions should all be 0.0 since (according to gbmentry.cpp) the intent is that new levels are treated as missing: 

```
iCatSplitIndicator = INTEGER(
            VECTOR_ELT(rCSplits,
                       (int)adSplitCode[iCurrentNode]))[(int)dX];
if(iCatSplitIndicator==-1)
{
   iCurrentNode = aiLeftNode[iCurrentNode];
}
else if(iCatSplitIndicator==1)
{
   iCurrentNode = aiRightNode[iCurrentNode];
}
else // categorical level not present in training
{
   iCurrentNode = aiMissingNode[iCurrentNode];
}
```

The problem is that `INTEGER(VECTOR_ELT(rCSplits, (int)adSplitCode[iCurrentNode]))` is of length equal to the number of levels in the train data, and yet the program retrieves values at positions
`11, 12, ..., 20` as these are the values of `(int)dX` in the test data. This can be easily verified by adding a `printf`. Surprisingly there is no segfault. The values at the addresses immediately following `INTEGER(VECTOR_ELT(rCSplits, (int)adSplitCode[iCurrentNode]))` appear in general not to be equal to `-1` or `1` and so in general the program correctly uses the missing node. However, by random chance if there is a `-1` or `1` the record will be scored at the left or right child respectively.

This is more illustrative:

```
                                    |-> shouldn't be accessing here
                                    |
[-1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 3245, 1, 64, 2342, 93348, -34857, 82, -8634, 9, 239]
                                          ^by chance this is a 1, so level 12 goes to 
                                           the right child instead of the missing node
```

**Comment by DexGroves** [comment]
Simple fix for this by changing lines 436+ of gbmentry.cpp: check if about to index rCSplits out of range, and skip straight to missing node.

Would be better to fix dX or rCSplits up front.

```
else // categorical
{
   if (LENGTH(VECTOR_ELT(rCSplits, (int)adSplitCode[iCurrentNode])) < (int)dX + 1) {
       iCurrentNode = aiMissingNode[iCurrentNode];
   } else {

       iCatSplitIndicator = INTEGER(
                   VECTOR_ELT(rCSplits,
                              (int)adSplitCode[iCurrentNode]))[(int)dX];
       if(iCatSplitIndicator==-1)
       {
          iCurrentNode = aiLeftNode[iCurrentNode];
       }
       else if(iCatSplitIndicator==1)
       {
          iCurrentNode = aiRightNode[iCurrentNode];
       }
       else // categorical level not present in training
       {
          iCurrentNode = aiMissingNode[iCurrentNode];
       }
    }
}
```

**Comment by pdmetcalfe** [comment]
Pull requests, including `testthat` tests, are welcome! :smile:

**Comment by pat-oreilly** [comment]
There are actually four places in gbmentry.cpp that need fixed.

I have a patch here:
https://github.com/PatrickOReilly/gbm/commit/2b1e19ca5b8fa026526382fb2aaf3caf70ad85cd
but haven't tested it extensively yet.

**Comment by pdmetcalfe** [comment]
Great - do send the pull request when you're ready!

We really need to tidy all the C++, I suspect - I've been putting it off
switching to Rcpp for some time.

On 19 March 2015 at 12:27, PatrickOReilly notifications@github.com wrote:

> There are actually four places in gbmentry.cpp that need fixed.
> 
> I have a patch here:
> PatrickOReilly@2b1e19c
> https://github.com/PatrickOReilly/gbm/commit/2b1e19ca5b8fa026526382fb2aaf3caf70ad85cd
> but haven't tested it extensively yet.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gbm-developers/gbm/issues/18#issuecomment-83536542.

## 

pdm

**Comment by pat-oreilly** [comment]
Will do.

**Comment by pdmetcalfe** [comment]
PS.

https://groups.google.com/forum/m/?hl=en#!forum/gbm-dev

pdm

**Comment by pat-oreilly** [comment]
Since `gbm_shrink_pred` and `gbm_shrink_gradient` are now gone, the only other place aside from `gbm_pred` where this logic appears is in `gbm_plot`:

```
else // categorical
{
    iCatSplitIndicator = INTEGER(
        VECTOR_ELT(rCSplits,
                   (int)adSplitCode[iCurrentNode]))[(int)dX];
    if(iCatSplitIndicator==-1)
    {
        aiNodeStack[cStackNodes] = aiLeftNode[iCurrentNode];
        cStackNodes++;
    }
    else if(iCatSplitIndicator==1)
    {
        aiNodeStack[cStackNodes] = aiRightNode[iCurrentNode];
        cStackNodes++;
    }
    else // handle unused level
    {
        iCurrentNode = aiMissingNode[iCurrentNode];
    }
}
```

Since `gbm_plot` does not take `newdata`, as I see it there is no chance of encountering a new level and so no fix is required here.

Thoughts?

**Comment by pdmetcalfe** [comment]
We should change gbm_plot, since with it in its current state it's in
principle possible to provoke core dumps from R code. (Admittedly by
crafting a deliberately broken gbm object, but even so.)

How unpleasant would it be to factor out the common code between gbm_pred
and gbm_plot?
