### ISSUE TITLE
Error: object 'gbm.fit' not found

### ISSUE THREAD

**Issue by dinggx** [gbm-developers/gbm3#25]
I followed the instruction and installed gbm package using install_github("gbm-developers/gbm") on R 3.1.1. After installation, I run the following in R:
library(gbm)
gbm.fit 
then I see the error message:
Error: object 'gbm.fit' not found
Any idea? Thanks.

**Comment by pdmetcalfe** [comment]
That'd be because we're halfway through tidying up our NAMESPACE and trying to find out what bits of our API are actually public.

`gbm:::gbm.fit` for now...
