### ISSUE TITLE
Encounter NaN depending on number of training observations and setting for shrinkage parameter in gbm.fit()

### ISSUE THREAD

**Issue by jimthompson5802** [gbm-developers/gbm3#29]
This was initially posted @harrysouthworth/gbm.  I understand this repo has taken over development of gbm.  I'm reposting here just for the record.

Depending on the number of observations used for training and setting of shrinkage parameter, I encounter the following problem in gbm.fit()

```
> mdl <- gbm.fit(x=train.df[,1:(ncol(train.df)-1)],
+                 y=train.df[,ncol(train.df)],
+                 distribution = "multinomial",
+   .... [TRUNCATED] 
Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        2.1972             nan     0.1000    0.6183
     2        1.8424             nan     0.1000    0.3274
     3        1.6543             nan     0.1000    0.2367
     4        1.5193             nan     0.1000    0.1802
     5        1.4185             nan     0.1000    0.1462
     6        1.3352             nan     0.1000    0.1213
     7        1.2657             nan     0.1000    0.0945
     8        1.2104             nan     0.1000    0.0811
     9        1.1629             nan     0.1000    0.0742
    10        1.1200             nan     0.1000    0.0609
    20        0.8972             nan     0.1000    0.0206
    40        0.7478             nan     0.1000    0.0040
    60        0.6810             nan     0.1000    0.0014
    80        0.6490             nan     0.1000       nan
   100           nan             nan     0.1000       nan
   120           nan             nan     0.1000       nan
   140           nan             nan     0.1000       nan
   150           nan             nan     0.1000       nan
```

This zip file contains source code and data to reproduce the problem:
https://drive.google.com/open?id=0B95myaZR5glcfm5XaXM3aGYyRkZQbG9hN1BBdElaNUVwcXVsZDdyN2tpMzYxeV94LWxyY28&authuser=0

**Comment by pdmetcalfe** [comment]
@gbm-developers/developers could someone else take a look at multinomial?  It looks to me like the train error and validation error are only based on the last class?

**Comment by gregridgeway** [comment]
My best guess is that the model ended up with a pure node and produced a large or numerically unstable terminal node prediction. This same issue was occurring with Bernoulli loss, which I addressed in https://github.com/gbm-developers/gbm/commit/8f9480373fa62272de105a4b2d1dd12661284a16. I am less familiar with the multinomial implementation, but perhaps a similar strategy would work there.

**Comment by pdmetcalfe** [comment]
Closing as multinominal-related.
