### ISSUE TITLE
roxygen2 documentation is incomplete

### ISSUE THREAD

**Issue by pdmetcalfe** [gbm-developers/gbm3#3]
The new `roxygen2` documentation is not yet complete: `R CMD check` gives warnings.

**Comment by harrysouthworth** [comment]
omg we have a milestone!

**Comment by harrysouthworth** [comment]
Sorry. It passed for me. Prolly forgot to push last edit...

**Comment by pdmetcalfe** [comment]
Hence reviewed pull requests :grinning:

**Comment by harrysouthworth** [comment]
I don't get the warning
- checking Rd files ... OK
- checking Rd metadata ... OK
- checking Rd cross-references ... OK
- checking for missing documentation entries ... OK
- checking for code/documentation mismatches ... OK
- checking Rd \usage sections ... OK
- checking Rd contents ... OK

Should've taken a branch... yeah, I know, sorry

**Comment by pdmetcalfe** [comment]
travis was still whinging.  Ho hum.  Fixed now, anyway.
