### ISSUE TITLE
INTEGER() can only be applied to a 'integer', not a 'double'

### ISSUE THREAD

**Issue by athhise** [gbm-developers/gbm3#33]
I  moved to this development version of gbm package  as suggested by @harrysouthworth  in his gbm repo (due to gbm.more bug with multinomial distribution). But after having download this one,  I ran into the issue below.
Issue occured on :
- window 7 64 bits
- R. 3.1.2 (2014.10.31)
- dependant variable is  multinomial 
- setting established as default as much as possible

![package issue and traceback](https://cloud.githubusercontent.com/assets/9213104/7120595/aba4c1a0-e1fd-11e4-8805-e241bd558773.PNG)

Notice that same error occurred even with the _demo_ of the package

![demo](https://cloud.githubusercontent.com/assets/9213104/7120680/521ba9cc-e1fe-11e4-897f-a3ab3a37941d.PNG)

**Comment by pdmetcalfe** [comment]
You're going to hate me, but It Works For Me (on Linux), so could you try and narrow it down in the C++?

**Comment by athhise** [comment]
Sorry @pdmetcalfe , It finally worked. I have no clue of what happened the first time

**Comment by pdmetcalfe** [comment]
No problem! :grin: It's always nice when the bugs just go away!
