### ISSUE TITLE
make gbm predict to handle poisson

### ISSUE THREAD

**Issue by spedygiorgio** [gbm-developers/gbm3#34]
According to current package user guide "The predictions from gbm do not include the offset term. The user may add the value of the offset to the predicted value if desired". Is it possible to accomodate this automatically?

**Comment by pdmetcalfe** [comment]
Patches welcome!

**Comment by gregridgeway** [comment]
gbm leaves it to you to add in the offset to the predictions. It is not obvious what offset you will want for the predictions. Perhaps in the data each case had a different exposure time. So you used `offset(log(exp.days))` in a gbm model with `distribution="poisson"`. But perhaps for your predictions you want to predict the predicted failure rate per year, not the predicted failure rate for a length equal to the time they were actually exposed. That means you need to add the offset that you want, like `exp(predict(my.gbm)+log(365))` or `exp(predict(my.gbm)+log(mydata$exp.days))`. You decide.
