### ISSUE TITLE
plot.gbm is broken?

### ISSUE THREAD

**Issue by DexGroves** [gbm-developers/gbm3#39]
CRAN's gbm successfully draws plots for me, but the gbm-developers version doesn't. CRAN's gbm seems to compile a lot faster.

Some code to reproduce: https://gist.github.com/DexGroves/c707129c7a3b63748204

**Comment by pdmetcalfe** [comment]
Yeah, compile times are slower with Rcpp.

**Comment by gregridgeway** [comment]
plot.gbm now fixed in https://github.com/gbm-developers/gbm/commit/771e8786ba7104ec11b04c8ca466aa969ac25e59
...and upon reviewing the CRAN version of gbm, I'm a little surprised that was working too.
