### ISSUE TITLE
Core parallelization of split point search algorithm

### ISSUE THREAD

**Issue by stefan-schroedl** [gbm-developers/gbm3#45]
With the latest GBM version, the option was introduced to parallelize cross validation by distribution to multiple cores. However, not every one uses cross validation all the time; it would be nice to parallelize the general algorithm as well. I am using GBM with large data files (millions of rows and hundreds of columns), and one run requires many hours.

90% of the GBM time is spent in the loop calculating the possible loss over all possible features/split points. The most effective way to parallelize this would be to distribute different feature subsets to different cores (the Yahoo proprietary GBT code solved it like this).

**Comment by gravesee** [comment]
I'll take a crack at this. Should be easy with openmp 

—

**Comment by stefan-schroedl** [comment]
Wow, excellent! Thanks a lot Zelazny7 for the quick response!

**Comment by pdmetcalfe** [comment]
RcppParallel ?

On 8 July 2015 at 01:32, Zelazny7 notifications@github.com wrote:

> I'll take a crack at this. Should be easy with openmp
> 
> —
> Sent from Mailbox
> 
> On Tue, Jul 7, 2015 at 6:24 PM, Stefan Schroedl notifications@github.com
> wrote:
> 
> > With the latest GBM version, the option was introduced to parallelize
> > cross validation by distribution to multiple cores. However, not every one
> > uses cross validation all the time; it would be nice to parallelize the
> > general algorithm as well. I am using GBM with large data files (millions
> > of rows and hundreds of columns), and one run requires many hours.
> > 90% of the GBM time is spent in the loop calculating the possible loss
> > over all possible features/split points. The most effective way to
> > parallelize this would be to distribute different feature subsets to
> > 
> > ## different cores (the Yahoo proprietary GBT code solved it like this).
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/gbm-developers/gbm/issues/45
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gbm-developers/gbm/issues/45#issuecomment-119381786.

## 

pdm

**Comment by pdmetcalfe** [comment]
Now done in dev.  It _was_ easy with openmp.  What wasn't easy were the two months of refactoring to make it easy to do with openmp. :smile:
