### ISSUE TITLE
Deprecate gbm.fit?

### ISSUE THREAD

**Issue by stefan-schroedl** [gbm-developers/gbm3#49]
Currently, the main training function is split between functions _gbm_ and _gbm.fit_. This leads to some code bloat and duplication (passing and (re)checking the arguments, extracting dimensions etc). In order to simplify the code, should we get rid of gbm.fit? It is not really necessary for users; the documentation states saving the time to generate the model frame, however for non-trivial applications I would think this would be a marginal fraction of the overall run time ... Thoughts?

**Comment by jeffwong** [comment]
As a user, not a developer, I frequently build the model frame myself and use *.fit functions from different packages. Please do not remove gbm.fit

**Comment by pdmetcalfe** [comment]
the duplication should now have gone away, so `gbm.fit` can live!
