### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by spedygiorgio** [gbm-developers/gbm3#52]
When training some GBM using caret it is impossible to use the gbm for prediction since the following error occurs:

 Error in object$var.levels[[i]] : subscript out of bounds 

It is possible to fix this issue?

**Comment by pdmetcalfe** [comment]
Can you give code and datasets, please, so that we can reproduce this?

**Comment by spedygiorgio** [comment]
You will find the code and data here: https://www.dropbox.com/sh/hpugfg73x9ucvmd/AAAtpH7nErnj0glovbhjsxHJa?dl=0

**Comment by spedygiorgio** [comment]
It has been solved following https://github.com/topepo/caret/issues/330. I would suggest gbm to accept in the input matrix also predictors not used in the model, instead of throwing error.

**Comment by thebamoor** [comment]
I second spedygiorgio 100%. GBM used to be able to accept columns not used in the model - why did the developers change this? That makes GBM more of a pain to use.
