### ISSUE TITLE
Laplace memory leak

### ISSUE THREAD

**Issue by harrysouthworth** [gbm-developers/gbm3#54]
From dereli fatih fatihdereli@yandex.com:

I am working for a clothing retail company in a position regarding forecasting. As a part of my job, I am responsible for maintaining and developing forecasting models in R. One of those models is GBM and we are having memory related issues while running GBM train codes which use GBM package. We are working on a virtual machine with the configuration of 32 GB RAM, 64-bit operating system and Intel Xeon 2.20 GHz CPU with 8 processors. The problem occurs while fitting models in GBM with laplace distribution. It does not happen when we try Gaussian distribution, code runs with a memory usage of 30% in a stable way. Laplace increases the memory gradually and it reaches to 100% which causes the software to stop. We tried to remove big objects and garbage cleaning, however it did not help. Current inputs for the gbm.fit function are bag fraction of 0.4, n.trees of 400, interaction.depth of 5, shrinkage of 0.025 and distribution of Laplace. Object size of the fitted object is 67 MB with 157k rows and 50 columns. We have seen bug fixes on Internet for multinomial distribution but did not have much result for the Laplace. Did you have any similar feedback from other people? Is there any bug fix for the Laplace, if not is it being planned to release such a bug fix?

**Comment by pdmetcalfe** [comment]
What version of the package, what's the data, what's the script?

**Comment by harrysouthworth** [comment]
I killed it. It's a repeat
