### ISSUE TITLE
Cannot search through "Code" in forked repo

### ISSUE THREAD

**Issue by ajkl** [gbm-developers/gbm3#57]
Hi all,

Since this is a forked repository, github code search does not work. What can be a good solution to get around that ?

**Comment by pdmetcalfe** [comment]
@harrysouthworth can you ask github support to make gbm-developers/gbm the network root rather than harrysouthworth/gbm ?

tl;dr we should have transferred the repo rather than forking it.

**Comment by harrysouthworth** [comment]
I've submitted the request

**Comment by harrysouthworth** [comment]
I'm told it's done. That was quick! I'm impressed.

Let me know if you're still having problems. Otherwise, I'll close this issue.

**Comment by ajkl** [comment]
Thanks @harrysouthworth !
But Search is still not working. Not sure why.
https://github.com/harrysouthworth/gbm/search?utf8=%E2%9C%93&q=pairwise
https://github.com/gbm-developers/gbm/search?utf8=%E2%9C%93&q=pairwise

**Comment by ajkl** [comment]
Works now.
