### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by wabee** [gbm-developers/gbm3#65]
It is likely that gbm contains a 'memory bug'. In general or at least when running a multinomial classification model in caret. Developers please review issue #263 in topepo/caret.
A single core task consumes all memory on a 16 Gb machine and doesn't return memory after the task is completed.

**Comment by harrysouthworth** [comment]
multinomial was throwing up all sorts of problems, including the one you note. We've now stripped it out of gbm altogether, the intention being to write a sister package that does nothing but multinomial at some point in the future. Please feel free to start that project yourself.

Thanks,
Harry

**Comment by pdmetcalfe** [comment]
As Harry says, we've given up on multinomial as a bad job - we don't do it at the moment.  If you can reproduce with the current development version of `gbm`, with one of the distributions that we currently support, please open another bug report.

Thanks!
