### ISSUE TITLE
Add coveralls or some other code coverage service

### ISSUE THREAD

**Issue by JackStat** [gbm-developers/gbm3#67]
I think we should add a code coverage service to help us identify areas of the code base that isn't backed up with good testing.  
codecov.io
coveralls.io
Plus we get a new badge to put in the readme :)

**Comment by pdmetcalfe** [comment]
Great idea!

[not sure I want to know what it'll tell me, though...]

**Comment by pdmetcalfe** [comment]
I knew I didn't want to know that!

Anyway, done.

**Comment by JackStat** [comment]
haha that is not too bad.  Thanks for doing that.  I will start working on improving that coverage.
