### ISSUE TITLE
Release tag for GBM 2.1.1

### ISSUE THREAD

**Issue by Neil-Schneider** [gbm-developers/gbm3#68]
CRAN is on GBM v2.1.1, but it is not clear what commit/hash that is related too. Can we get a release tag set at this commit?

**Comment by pdmetcalfe** [comment]
Thanks for volunteering to work it out? :smile:

**Comment by harrysouthworth** [comment]
I think it was on googlecode at the time. Not sure everything was ported

**Comment by gregridgeway** [comment]
Are we ready to change the version in the DESCRIPTION to version 2.2 and post the current GitHub version to CRAN?

**Comment by JackStat** [comment]
I don't think that we will want to release this with the false warnings that are occurring for the bernoulli dist gbm runs #69

**Comment by Neil-Schneider** [comment]
Well, I found the commit for v2.1 - https://github.com/gbm-developers/gbm/commit/d8d9589d9cf8f0c3a7664df9ec1c071ca81674e2 

No luck finding the v2.1.1 commit. It appears to be a branch off v2.1 to change test.gbm.R. The RUnit namespace was added to the checkTrue function calls.

I guess tagging the v2.1 release is about a close as we can get.

**Comment by pdmetcalfe** [comment]
We get there eventually... done.
