### ISSUE TITLE
Setting seed yields different results on mac for multicore gbm

### ISSUE THREAD

**Issue by JackStat** [gbm-developers/gbm3#72]
This test fails on my mac

```
test_that("Setting the seed causes result to be reproducible (multicore)", {
  skip_on_cran()
  set.seed(18900217)
  mod <- gbm(Species == 'setosa' ~ ., data=iris, distribution="bernoulli",
             cv.folds=3, n.trees=100, shrinkage=.1)
  nt1 <- gbm.perf(mod, method="cv", plot.it=FALSE)
  ri1 <- relative.influence(mod, n.trees=nt1)

  set.seed(18900217)
  mod <- gbm(Species == 'setosa' ~ ., data=iris, distribution="bernoulli",
             cv.folds=3, n.trees=100, shrinkage=.1)
  nt2 <- gbm.perf(mod, method="cv", plot.it=FALSE)
  ri2 <- relative.influence(mod, n.trees=nt2)

  expect_equal(nt1, nt2,
               label="Number of trees match when same seed is used")
  expect_equal(ri1, ri2,
               label="Relative influences match when same seed is used")
})
```

I am wondering if we should add mac osx to our travis builds
http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by pdmetcalfe** [comment]
Any idea?

https://travis-ci.org/pdmetcalfe/gbm/jobs/90346687

pdm

**Comment by JackStat** [comment]
I wonder if you need to add something to get lgfortran to work properly

```
before_install:
  - brew update
  - brew install gfortran
```

**Comment by pdmetcalfe** [comment]
Nope, it's not that.  `gfortran` is (apparently) part of `gcc`, and `gcc` is already installed (after some experimentation).

Might it be this:

http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

[Never used a Mac, so you're on your own a bit with this.]

**Comment by JackStat** [comment]
Nice find on the article.  How about this

```
before_install:
  - brew install homebrew/versions/gcc48
```

**Comment by pdmetcalfe** [comment]
Nope: gcc48 already installed.

My (ahem) exhaustive googling hasn't revealed anything obvious about travis, R, and os X, so I'm a bit stuck.

**Comment by pdmetcalfe** [comment]
I've seen this too, not on Mac.  But I think it's about to go away if we move the parallelization into the C++ layer.  Any chance you could test out the dev version on a Mac to work out how openmp works there?

**Comment by pdmetcalfe** [comment]
I don't think this is now possible, so closing...
