### ISSUE TITLE
Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by harrysouthworth** [gbm-developers/gbm3#73]
Hello,
   I have been getting an  "Error in checkForRemoteErrors(val) : one node produced an error: incorrect number of dimensions"
  in some  gbm   cv.folds > 1 runs.   cv.folds = 0 runs OK.   ( in some larger data set runs the rgui has shutdown)

Here is a reproducible example.
library(gbm)

  test = data.frame(
Y = c( 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1 ) ,
R= as.factor(  c( 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,
     2,2,2,2,2,3,3,3,3,3,4,4,1,1,1,1,1,1,1,2,2,3,3,4,4 ) )
       )
str(test)

set.x =
 gbm(  Y ~ R      ,
      data=  test      ,
      var.monotone=NULL     ,
      distribution="bernoulli",
      n.trees=         10  ,
      shrinkage=       .01 ,
      interaction.depth= 1 ,
      bag.fraction =     1,
      train.fraction =   1,
      n.minobsinnode =   2,
      cv.folds =         2,
      keep.data=TRUE,
      verbose=F,
      n.cores=1)

sessionInfo()

 output:

Error in checkForRemoteErrors(val) :
  one node produced an error: incorrect number of dimensions

> sessionInfo()

R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] parallel  splines   stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] gbm_2.1.1       lattice_0.20-33 survival_2.38-3

loaded via a namespace (and not attached):
[1] grid_3.2.2

>  Thanks,

Van L. Parsons
National Center for Health Statistics
E-mail: vparsons@cdc.gov

**Comment by gregridgeway** [comment]
My guess is somewhere there is a [,] that needs to be [,,drop=FALSE]. With one feature there’s probably some place that the cross-validation is dropping one of the dimensions. I’ll poke around.

Greg

**Comment by gregridgeway** [comment]
No errors with gbm 2.1-06, the version that is on github.

Run

library("devtools")

install_github("gbm-developers/gbm")

Greg

**Comment by gregridgeway** [comment]
Post shows the user was using gbm 2.1.1, not the latest version on GitHub, which does not generate an error.

**Comment by gregridgeway** [comment]
That works,
Thanks -  Van Parsons

From: Greg Ridgeway [mailto:gregridgeway@gmail.com]
Sent: Monday, November 23, 2015 4:55 PM
To: 'gbm-developers/gbm' reply@reply.github.com; 'gbm-developers/gbm' gbm@noreply.github.com
Cc: Parsons, Van L. (CDC/OPHSS/NCHS) vlp1@cdc.gov
Subject: RE: [gbm] Error in checkForRemoteErrors(val) (#73)

No errors with gbm 2.1-06, the version that is on github.

Run
library("devtools")
install_github("gbm-developers/gbm")

Greg
