### ISSUE TITLE
GBM crashing consistently on Mac OS X (10.9.4)

### ISSUE THREAD

**Issue by harrysouthworth** [gbm-developers/gbm3#8]
_From @kgoldfeld on September 9, 2014 2:16_

Every call to gbm (from package version 2.1, R version 3.1.1) on my Mac causes R to abort.  Is this a known issue?

![screen shot 2014-09-08 at 10 14 17 pm](https://cloud.githubusercontent.com/assets/5994273/4195784/527248c2-37c7-11e4-8eb7-f85371c321df.png)

_Copied from original issue: harrysouthworth/gbm#27_

**Comment by harrysouthworth** [comment]
Sorry, I've never seen that before so far as I recall. Do you get the same problem with very simple examples? What if you set n.cores=1?

**Comment by harrysouthworth** [comment]
_From @kgoldfeld on September 9, 2014 13:39_

Thanks for getting back to me so quickly.  It still crashes, even with n.cores=1.

This is my code (taken from the gbm help file):

library(gbm)
N <- 1000
X1 <- runif(N)
X2 <- 2_runif(N)
X3 <- ordered(sample(letters[1:4],N,replace=TRUE),levels=letters[4:1])
X4 <- factor(sample(letters[1:6],N,replace=TRUE))
X5 <- factor(sample(letters[1:3],N,replace=TRUE))
X6 <- 3_runif(N)
mu <- c(-1,0,1,2)[as.numeric(X3)]

SNR <- 10 # signal-to-noise ratio
Y <- X1**1.5 + 2 \* (X2**.5) + mu
sigma <- sqrt(var(Y)/SNR)
Y <- Y + rnorm(N,0,sigma)

data <- data.frame(Y=Y,X1=X1,X2=X2,X3=X3,X4=X4,X5=X5,X6=X6)

# fit initial model

gbm1 <-
  gbm(Y~X1+X2+X3+X4+X5+X6,         # formula
      data=data,                   # dataset
      var.monotone=c(0,0,0,0,0,0), # -1: monotone decrease,
      # +1: monotone increase,
      #  0: no monotone restrictions
      distribution="gaussian",     # see the help for other choices
      n.trees=1000,                # number of trees
      shrinkage=0.05,
      n.cores=1)

I just ran this in R (previously, I had been running from Rstudio), and this is the error message I received:

 **\* caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: .Call("gbm", Y = as.double(y), Offset = as.double(offset), X = as.double(x),     X.order = as.integer(x.order), weights = as.double(w), Misc = as.double(Misc),     cRows = as.integer(cRows), cCols = as.integer(cCols), var.type = as.integer(var.type),     var.monotone = as.integer(var.monotone), distribution = as.character(distribution.call.name),     n.trees = as.integer(n.trees), interaction.depth = as.integer(interaction.depth),     n.minobsinnode = as.integer(n.minobsinnode), n.classes = as.integer(nClass),     shrinkage = as.double(shrinkage), bag.fraction = as.double(bag.fraction),     nTrain = as.integer(nTrain), fit.old = as.double(NA), n.cat.splits.old = as.integer(0),     n.trees.old = as.integer(0), verbose = as.integer(verbose),     PACKAGE = "gbm")
 2: gbm.fit(x, y, offset = offset, distribution = distribution, w = w,     var.monotone = var.monotone, n.trees = n.trees, interaction.depth = interaction.depth,     n.minobsinnode = n.minobsinnode, shrinkage = shrinkage, bag.fraction = bag.fraction,     nTrain = nTrain, keep.data = keep.data, verbose = lVerbose,     var.names = var.names, response.name = response.name, group = group)
 3: gbm(Y ~ X1 + X2 + X3 + X4 + X5 + X6, data = data, var.monotone = c(0,     0, 0, 0, 0, 0), distribution = "gaussian", n.trees = 1000,     shrinkage = 0.05, n.cores = 1)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

Let me know if you would like a core dump or any other info.
- Keith

**Comment by harrysouthworth** [comment]
_From @Mahalanobis on December 5, 2014 18:1_

I have the same problem, but this disappear when i don't use mFeatures parameter...

**Comment by pdmetcalfe** [comment]
Could someone either
1. Buy me a Mac, or
2. Work out where the crash is?

Thanks!

**Comment by pdmetcalfe** [comment]
Anyone care about this?

**Comment by JackStat** [comment]
We could always add an R version requirement in the description

```
Depends:
    R (>= 3.1.2)
```

**Comment by pdmetcalfe** [comment]
Not sure this is R version related. I'd like to know if it's present in the dev GBM version, or at least find out more about it. Unexplained segfaults scare me.

**Comment by pdmetcalfe** [comment]
We've done quite a lot of work on tidying allocation and whatnot, and have ubsan'd the code, so I'm going to close this as no longer current.
