### ISSUE TITLE
training after the refactoring(b1628fc) is much slower

### ISSUE THREAD

**Issue by entelechie** [gbm-developers/gbm3#83]
before the refactoring, the training on a 100k toys data set with depth 3 and 100 trees finishes in 5 minutes..
after the b1628fc, it takes hours....

from my superficial understanding, looks like:
0. nodes' best split are no longer cached: previously, only new nodes' best split will be calculated from a portion of data, but now we re-calculate all nodes in each iteration; 
1. an extra loop[2] on node has been introduced. because of the cache's absence, it makes thing even slower.

[1] https://github.com/gbm-developers/gbm/blob/22a019d25e1527f5bcf4ae1825fdf79eeec2f5e6/src/node_search.cpp#L56
[2] https://github.com/gbm-developers/gbm/blob/master/src/node_search.cpp#L47

**Comment by pdmetcalfe** [comment]
Yup, we knew this was likely.

@jhickeyPhysics can you take a look?

**Comment by pdmetcalfe** [comment]
Patch under development...

**Comment by pdmetcalfe** [comment]
@jhickeyPhysics take a look at pdmetcalfe/gbm@93faf2796a5f1eed7c27f2a4534431b578961c2e

**Comment by jhickeyPhysics** [comment]
@pdmetcalfe Excellent! Inlining the pimpl'ed dataset does make a good chunk of a difference.  It appears to be a combination of several things: inlining, order of loops, caching splits, memory allocation etc. leading to the loss in efficiency.  I'm working through the tree growing patch identifying the effects of all of these on efficiency and developing a patch.

**Comment by pdmetcalfe** [comment]
Done.
