### ISSUE TITLE
testthat error on Mac OS X 10.11.5

### ISSUE THREAD

**Issue by bobthecat** [gbm-developers/gbm3#99]
> devtools::check()
> Updating gbm documentation
> Loading gbm
> Setting env vars ---------------------------------------------------------------
> CFLAGS  : -Wall -pedantic
> CXXFLAGS: -Wall -pedantic
> Building gbm -------------------------------------------------------------------
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
>   --no-save --no-restore --quiet CMD build '/Users/druau/stuff/gbm' --no-resave-data --no-manual 

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
- checking for file ‘/stuff/gbm/DESCRIPTION’ ... OK
- preparing ‘gbm’:
- checking DESCRIPTION meta-information ... OK
- cleaning src
- installing the package to build vignettes
- creating vignettes ... OK
- cleaning src
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- building ‘gbm_2.1.06.9000.tar.gz’
  Warning: invalid uid value replaced by that for user 'nobody'
  Warning: invalid gid value replaced by that for user 'nobody'

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking gbm -------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/cr/x4x8pv151zqgktflqn3sz3cnl3mln2/T//Rtmp3TJXzI/gbm_2.1.06.9000.tar.gz'  \
  --as-cran --timings --no-manual 
- using log directory ‘/private/var/folders/cr/x4x8pv151zqgktflqn3sz3cnl3mln2/T/Rtmp3TJXzI/gbm.Rcheck’
- using R version 3.3.0 (2016-05-03)
- using platform: x86_64-apple-darwin13.4.0 (64-bit)
- using session charset: UTF-8
- using options ‘--no-manual --as-cran’
- checking for file ‘gbm/DESCRIPTION’ ... OK
- this is package ‘gbm’ version ‘2.1.06.9000’
- checking package namespace information ... OK
- checking package dependencies ... OK
- checking if this is a source package ... OK
- checking if there is a namespace ... OK
- checking for executable files ... OK
- checking for hidden files and directories ... OK
- checking for portable file names ... OK
- checking for sufficient/correct file permissions ... OK
- checking whether package ‘gbm’ can be installed ... OK
- checking installed package size ... OK
- checking package directory ... OK
- checking ‘build’ directory ... OK
- checking DESCRIPTION meta-information ... OK
- checking top-level files ... OK
- checking for left-over files ... OK
- checking index information ... OK
- checking package subdirectories ... OK
- checking R files for non-ASCII characters ... OK
- checking R files for syntax errors ... OK
- checking whether the package can be loaded ... OK
- checking whether the package can be loaded with stated dependencies ... OK
- checking whether the package can be unloaded cleanly ... OK
- checking whether the namespace can be loaded with stated dependencies ... OK
- checking whether the namespace can be unloaded cleanly ... OK
- checking loading without being on the library search path ... OK
- checking dependencies in R code ... OK
- checking S3 generic/method consistency ... OK
- checking replacement functions ... OK
- checking foreign function calls ... OK
- checking R code for possible problems ... OK
- checking Rd files ... OK
- checking Rd metadata ... OK
- checking Rd line widths ... OK
- checking Rd cross-references ... OK
- checking for missing documentation entries ... OK
- checking for code/documentation mismatches ... OK
- checking Rd \usage sections ... OK
- checking Rd contents ... OK
- checking for unstated dependencies in examples ... OK
- checking line endings in C/C++/Fortran sources/headers ... OK
- checking compiled code ... OK
- checking sizes of PDF files under ‘inst/doc’ ... OK
- checking installed files from ‘inst/doc’ ... OK
- checking files in ‘vignettes’ ... OK
- checking examples ... OK
  Examples with CPU or elapsed time > 5s
   user system elapsed
  gbm 4.592  0.164   5.031
- checking for unstated dependencies in ‘tests’ ... OK
- checking tests ...
  Running ‘testthat-a.R’
  Running ‘testthat-b.R’ [45s/45s]
  Running ‘testthat-c.R’
  Running ‘testthat-d.R’
  Running ‘testthat-e.R’
  Running ‘testthat-f.R’
  ERROR
  Running the tests in ‘tests/testthat-f.R’ failed.
  Last 13 lines of output:
       tied.times.method, prior.node.coeff.var, strata, patient.id, n.threads)
  4: gbmCluster(n.cores)
  5: parallel::makeCluster(n)
  6: makePSOCKcluster(spec, ...)
  7: .check_ncores(length(names))
  8: stop(msg, call. = TRUE)
  
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 1
  1. Error: gaussian works in parallel (@test-foldid.R#31) 
  
  Error: testthat unit tests failed
  Execution halted
- checking for unstated dependencies in vignettes ... OK
- checking package vignettes in ‘inst/doc’ ... OK
- checking re-building of vignette outputs ... OK
- DONE

Status: 1 ERROR
See
  ‘/private/var/folders/cr/x4x8pv151zqgktflqn3sz3cnl3mln2/T/Rtmp3TJXzI/gbm.Rcheck/00check.log’
for details.

R CMD check results
1 error  | 0 warnings | 0 notes
checking tests ... ERROR
Running the tests in ‘tests/testthat-f.R’ failed.
Last 13 lines of output:
         tied.times.method, prior.node.coeff.var, strata, patient.id, n.threads)
  4: gbmCluster(n.cores)
  5: parallel::makeCluster(n)
  6: makePSOCKcluster(spec, ...)
  7: .check_ncores(length(names))
  8: stop(msg, call. = TRUE)

  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 1
1. Error: gaussian works in parallel (@test-foldid.R#31) 
   
   Error: testthat unit tests failed
   Execution halted

**Comment by pdmetcalfe** [comment]
My guess is that you don't have a matching gbm installed in your R system.  Because of the way that cv.folds parallelism works (by forking and doing require(gbm)) it needs a matching gbm in your R install.

**Comment by pdmetcalfe** [comment]
No longer current; closing.
